# Generated by Django 6.0.6 on 2026-06-24 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_application_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['id'], 'verbose_name_plural': 'companies'},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['id']},
        ),
    ]
